module.exports={
    name: "routes",
    columns: {
        RouteOID:{
            primary: true,
            type:Number,
            generated: true
        },
        RouteOIDParent:{
            type:Number,
            default:-1
        },
        SortNumber:{
            type:Number,
            nullable:true
        },
        RouteType:{
            type:Number,
            comment:'1:models，2:views'
        },
        RouteName:{
        	length:200,
            type:String,
            nullable:true
        },
        RoutePath:{
            length:200,
            type:String
        },
        RouteMethod:{
            length:50,
            type:String,
            nullable:true
        },
        RouteImgSrc:{
            length:500,
            type:String,
            nullable:true
        }
    },
    uniques:[
        {
            name:"RouteType_RoutePath_RouteMethod",
            columns:[
                "RouteType",
                "RoutePath",
                "RouteMethod"
            ]
        }
    ]
};