module.exports={
    name: "live",
    columns: {
        OID:{
            primary: true,
            type:Number,
            generated: true
        },
        openPush:{
            type:Boolean,
            default:0
        },
        openLive:{
            type:Boolean,
            default:1
        },
        saveLocal:{
            type:Boolean,
            default:1
        },
        folderClassifiyAsTime:{
            type:Boolean,
            default:1
        },
        working:{
            type:Boolean,
            default:0
        },
        deviceName:{
            length:255,
            type:String
        },
        liveSourceHead:{
        	length:255,
            type:String,
            nullable:true
        },
        streamUrl:{
            length:500,
            type:String
        },
        pushPaths:{
            length:500,
            type:String
        },
        savePath:{
            length:500,
            type:String,
            default:''
        },
        saveFileName:{
            length:255,
            type:String,
            nullable:true
        },
        splitVideoType:{
            length:255,
            type:String,
            default:'time'
        },
        splitVideoValue:{
            length:255,
            type:String,
            default:'02:00:00'
        },
        folderClassifiyAsTimeType:{
            length:255,
            type:String,
            default:'YYYY-MM-DD'
        },
        OfflineAlertEmails:{
            length:1000,
            type:String,
            nullable:true
        }
    }
};